### PR TITLE
use docker for android related build

### PR DESCRIPTION
**Pull request by gengjiawen**
## what is being fixed
Currently ci in master failed due to ndk version
## how is it fixed
use the android docker same as react-native (which include buck, ndk,=)
## why is docker being added.
see above.

### CODE REVIEW

**Comment by davidaurelio** [comment]
Thank you for your contribution. Would you mind filling in the description?

- what is being fixed 
- how is it fixed 
- why is docker being added.

**Comment by gengjiawen** [comment]
> Thank you for your contribution. Would you mind filling in the description?
> 
> * what is being fixed
> * how is it fixed
> * why is docker being added.

I add them in PR description.

**Comment by gengjiawen** [comment]
@davidaurelio ping.

**Comment by davidaurelio** [comment]
Is this still relevant? It seems we got CI going again without docker.

**Comment by gengjiawen** [comment]
> Is this still relevant? It seems we got CI going again without docker.

Yeap.
Travis CI android env has buck, ndk is old.
This docker is used by `react-native` repo too.

**Review by NickGerleman — CHANGES_REQUESTED** [review]
Since this PR, infrastructure has moved to GitHub Actions. I'm going to take a stab at adding to it, but so far setup hasn't been a source of too much instability (though I'm sure this will change with more tasks). Regardless, this change would need to be updated for GitHub Actions.

**Pull request closed without merging**
