### PR TITLE
Fix align-content: center, flex-end alignment with margin

### PR DESCRIPTION
**Pull request by woehrl01**
This fixes ```align-content: center``` and ```align-content: flex-end``` when the child exceeds the parents size. See #476. It also fixes those layouts if the child has ```margin: auto``` set.

### CODE REVIEW

**Comment by woehrl01** [comment]
> I am not 100% certain with this change, as there isn't any failing test after removing those lines. According to git those lines have been added by @rigdern . Do you have an example layout where this line are required?

After looking deeper into this, and trying to add failing tests, I found that it fails even without margin set, and also has an addional bug there with ```margin: auto```. I'm now a lot more certain that this is a valid fix.

**Comment by rigdern** [comment]
> I am not 100% certain with this change, as there isn't any failing test after removing those lines. According to git those lines have been added by @rigdern . Do you have an example layout where this line are required?

@woehrl01 When you say "removing those lines", I believe you are referring to:

```
if (measureModeCrossDim == YGMeasureModeAtMost) {
  containerCrossAxis = fminf(containerCrossAxis, availableInnerCrossDim);
}
```

I don't have a specific example available. It looks like those lines were added in #185 which involved significant changes to the layout engine in order to make it better match the [W3C flexbox spec](https://www.w3.org/TR/css-flexbox-1/).

#476 didn't repro in the version of the layout engine that is included in React Native 0.32.0-rc.0. So it seems those lines didn't break this scenario back then.

If you delete those lines, what prevents the calculated cross size from exceeding the available cross size when running in the at-most measure mode?

**Comment by woehrl01** [comment]
> #476 didn't repro in the version of the layout engine that is included in React Native 0.32.0-rc.0. So it seems those lines didn't break this scenario back then.

That's strange. 

> If you delete those lines, what prevents the calculated cross size from exceeding the available cross size when running in the at-most measure mode?

Nothing prevents it. But as the resulting value is only used for the ```alignItem```/```margin: auto``` step, this value shouldn't be clipped, as the child is still bigger then ```AT_MOST``` wants it.

I just want to share my findings, as I'm still not that convinced. But I also don't understand why that value should be clipped either.

**Comment by rigdern** [comment]
@woehrl01 The test case I listed in #476 is still laid out incorrectly in master.

**Comment by woehrl01** [comment]
@rigdern that's strange, as I added [a test case with exactly your values](https://github.com/facebook/yoga/blob/master/gentest/fixtures/YGAlignItemsTest.html#L147-L151), which doesn't fail in the master. Could you please verify if I correctly adapted your failing layout?

**Comment by rigdern** [comment]
@woehrl01 The test case I reported used a `position: absolute` element on the root with a non-zero value for `left`. Here's the diff: https://www.diffchecker.com/BD9BgS4m

**Comment by woehrl01** [comment]
@rigdern Oh, thanks, I see! It's not the root node which isn't laid out correctly, I'll have a look. 🔨

**Pull request closed without merging**
