### PR TITLE
Increase that number of bit in YGStyle and YGLayout to resolve the sign issue.

### PR DESCRIPTION
**Pull request by anyktx**
This may not be the best way to solve the issue of [https://github.com/facebook/yoga/issues/845], but it is an effective one.

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
+1 to get this in the bank if possible. My C++ compiler refuses to build YGNode.h because of the implicit truncation changing the sign of the value from 4 to -4.

**Comment by Adlai-Holler** [comment]
@davidaurelio One way to fix this simply is to change `YG_ENUM_BEGIN` from `int` to `unsigned`

**Comment by Adlai-Holler** [comment]
cc #870

**Comment by davidaurelio** [comment]
I fixed this last August. However, I cannot close here since I am no longer at FB.

**Pull request closed without merging**
