### PR TITLE
Rename YGUnitPixel to YGPoint...

### PR DESCRIPTION
**Pull request by hartbit**
...to reflect the modern world we live in with dynamic DPI platforms :)

### CODE REVIEW

**Comment by dshahidehpour** [comment]
Thanks @hartbit. This looks good to me, but I'll leave it upto @emilsjolander to merge it.

**Comment by emilsjolander** [comment]
I'll get to this on monday. Thanks @hartbit !

**Comment by hartbit** [comment]
The build failures seem unrelated...

**Comment by emilsjolander** [comment]
@hartbit agreed. I've had a lot of other stuff to deal with today. I'm going to try to look at both this PR and the failing tests tomorrow or Wednesday. The PR looks good though so don't let this block you from working on the next PR in the chain 👍

**Comment by hartbit** [comment]
@emilsjolander No worries :) I have pretty much finished the percentage value adaptation, but I have similar errors and I'd like to know for sure I didn't cause any before opening a PR, so let me know whenever you've figured the current ones out. Thx!

**Comment by emilsjolander** [comment]
@hartbit Seems unrelated 👍

**Comment by emilsjolander** [comment]
Could you squash & rebase. The PR failed to import

**Comment by hartbit** [comment]
@emilsjolander I'm not a git guru :) Can you confirm that those are the steps you want me to take?

1. `git rebase -i HEAD~3`
2. `git rebase master`

**Comment by emilsjolander** [comment]
No need to squash, just rebase (copy pasted same message in multiple PRs :p) I'm not git pro either but have a look at https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by emilsjolander** [comment]
@hartbit did you figure it out?

**Comment by hartbit** [comment]
@emilsjolander I think I did the rebase correctly.

**Comment by emilsjolander** [comment]
@hartbit Sadly no. If you look at the file changes and commits in this PR it now contains a lot of other commit. Re-apply your commit to the latest master and push / force push it onto your remote branch.

**Comment by hartbit** [comment]
@emilsjolander Figured it out :)

**Comment by emilsjolander** [comment]
@hartbit FYI I'll rename `roundToPointGrid` back to `roundToPixelGrid` before landing. At some point we will want to support point scale factor to round to pixel grid even though input is points.

**Comment by hartbit** [comment]
👍🏻

**Pull request closed without merging**
