### PR TITLE
Add YGLayoutGetBorder, counterpart of YGLayoutGetPadding

### LINKED ISSUE #326: Content box
Now that percent unit support has been added to the library, I was wondering if you've considered exposing the content box on top of the element box. What do you think? It currently seems hard to know the exact size of the padding inside the box.

### PR DESCRIPTION
**Pull request by arcanis**
Followup of #335, fix #326. This commit add the `YGLayoutGetBorder(node, edge)` function, which correctly takes RTL/LTR into account when resolving `EDGE_START` & `EDGE_END`.

### CODE REVIEW

**Comment by arcanis** [comment]
@emilsjolander Can you publish a release on npm once this PR is merged? Due to this repository being monolithic by design, the package cannot be used with npm and yarn without performing a manual clone :)

**Comment by emilsjolander** [comment]
@arcanis sure, I can do this later this week or early next week.

**Comment by emilsjolander** [comment]
@arcanis What should I do to publish this on npm? I'm new to that whole ecosystem.

**Comment by emilsjolander** [comment]
@arcanis Also could you have a look at the js tests failing on travis?

**Comment by arcanis** [comment]
I think the tests are failing because the `javascript/build/Release/nbind.js` file hasn't been regenerated after one of the breaking changes - I've just pulled the repo, rebuilt it, and everything passed (this theory is supported by the fact that the native module tests are passing, which makes sense because they are automatically rebuilt when running `npm install`).

As for publishing, first ensure you have an npm account (I'm not sure if fb requires projects to be published under an umbrella account) by running `npm adduser` - If you don't have one, it should create it automatically. Otherwise, it will log you in.

**Publish the first release:**

  - Jump into the javascript directory
  - Run `npm run build:all`
  - Run `npm publish`

**Publish future releases:**

  - Jump into the javascript directory
  - Run `npm run build:all`
  - Run `npm version <major/minor/patch>` (will respectively bump major/minor/patch version number)
  - Run `npm publish`

If you want, I can publish the initial release then give you access to the package.

**Comment by emilsjolander** [comment]
@arcanis I can give it a try! thanks

**Pull request closed without merging**
