### PR TITLE
Fix right/bottom in absolute layout.

### PR DESCRIPTION
**Pull request by yihuang**
1, Change bottom to be based on height of parent.
2, Respect margin value when layout with right/bottom.

### CODE REVIEW

**Comment by woehrl01** [comment]
@yihuang It would be great if you could add a test for this change. You simple have to add a html layout inside the fixture folder and run `gentest.rb`.

**Comment by yihuang** [comment]
@woehrl01 When I run ``ruby gentest.rb``, i got error, i'm running with ruby 2.4.1:

```
/usr/local/lib/ruby/gems/2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/table_cell.rb:3:in `alias_method': undefined method `col_span' for class `Watir::TableCell' (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/table_cell.rb:3:in `<class:TableCell>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/table_cell.rb:2:in `<module:Watir>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver/elements/table_cell.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/watir-webdriver-0.9.9/lib/watir-webdriver.rb:119:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from gentest.rb:3:in `<main>'
```

**Comment by woehrl01** [comment]
@yihuang looks like an incompatibility with ruby 2.4.*. see https://github.com/watir/watir/issues/508. I use ruby 2.2.1 locally. Maybe @emilsjolander know more about this?

**Comment by emilsjolander** [comment]
Looks line the issue is closed. Maybe we can just upgrade our watir dep?

**Comment by emilsjolander** [comment]
@yihuang Try running with ruby 2.2. I agree with @woehrl01 we want a test to ensure we don't regress this in the future.

**Comment by yihuang** [comment]
@woehrl01 tests has been added.

**Comment by woehrl01** [comment]
Thank you @yihuang! 
As travis fails I run the tests locally, looks good to me @emilsjolander.

**Pull request closed without merging**
