### PR TITLE
Entry point without TLA for js package

### PR DESCRIPTION
**Pull request by bbohlender**
Follow up on #1637 

TLDR: tooling for TLA is not there yet; An additional entry point without top-level-await is appropriate

- adds ./load entry to js package
- uses .js file extensions to prevent requiring [allowImportingTsExtensions](https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions)

### CODE REVIEW

**Comment by NickGerleman** [comment]
> uses .js file extensions to prevent requiring [allowImportingTsExtensions](https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions)

We are already doing this in the babel transform during packing. 

IMG_0512

**Comment by NickGerleman** [comment]
It looks like the Jest environment didn’t like the extension change.

The model in the repo right now is that when Yoga is published, its package entry point is changed to be written to babel generated JS, along with rewriting imports. But still include original sources as well.

**Review by NickGerleman — CHANGES_REQUESTED** [review]
Current change seems to be breaking the dev-time builds and scripts which transform the typescript on the fly.

**Comment by bbohlender** [comment]
Sorry for my confusion

**Review by NickGerleman — APPROVED** [review]

**Comment by NickGerleman** [comment]
@bbohlender would you be able to give this a quick mention in the package readme?

**Comment by bbohlender** [comment]
@NickGerleman, for sure! Is that, what you had in mind?

**Comment by NickGerleman** [comment]
That looks great. Thanks for this PR!

**Pull request closed without merging**
