### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by eduardogch**
Just add .editorconfig into yoga 😄

### CODE REVIEW

**Comment by emilsjolander** [comment]
Looks good. Please sign the CLA and I'll merge this :)

**Comment by eduardogch** [comment]
Sign CLA

**Comment by emilsjolander** [comment]
@eduardogch how did you sign it? our tools haven't picked it up :/

**Comment by eduardogch** [comment]
Sent an email to cla@fb.com, hopefully they help me with the process

**Comment by eduardogch** [comment]
ohh that was fast! we are ready to merge @emilsjolander

**Pull request closed without merging**
