### PR TITLE
Fix xmlns import for android yoga library

### PR DESCRIPTION
**Pull request by woehrl01**
Fix xmlns import for yoga library by using `apk` instead of `lib` in the comment.

### CODE REVIEW

**Comment by emilsjolander** [comment]
Actually shouldn't it be apk/lib?

cc @rspencer01

**Comment by woehrl01** [comment]
could be too, I'm not that familiar with android, but at least this was the thing I had to change to make a working/compilable example project.

**Comment by rspencer01** [comment]
I am not certain, but a google search suggests `apk/res`.  Give that a go?  I'd be more happy with that than `apk`.

**Comment by woehrl01** [comment]
How about `http://schemas.android.com/apk/res-auto` ? Which is the suggestion Android Studio makes.

**Comment by rspencer01** [comment]
I object to that because it pulls in everything.  We had trouble back when we had attributes like

    yoga:height

that conflicted with some other library's definition of `height`.  We don't want to do this to other people (as unlikely as it may be).  What was it breaking, out of interest?

**Comment by woehrl01** [comment]
It didn't compile 😅

I created a complete new project with a different namespace, added the gradle imports, copied the example xml layout. And this was the necessary change which costed me some hours 😂

**Comment by rspencer01** [comment]
Ok.  Well, this is a minor change, its really not worth anybody losing sleep about.

**Pull request closed without merging**
