### PR TITLE
Feature hidden nodes

### PR DESCRIPTION
**Pull request by roxlu**

### CODE REVIEW

**Comment by emilsjolander** [comment]
I like the suggestion @woehrl01 had in #241 about using the `display` property from css. So add an enums with values `none` and `flex`. What do you think?

**Comment by emilsjolander** [comment]
@roxlu Are you planning to update this?

**Comment by roxlu** [comment]
@emilsjolander Yes, I'll fix that this weekend. Sorry for not replying earlier.

**Comment by emilsjolander** [comment]
Np! Just checking in :) no rush

**Comment by joce** [comment]
Hey @roxlu This is a feature we'd definitely need. However, having it as a property is is must for us. Tests are also required. 
Do you have any plans to update to a property and to write tests? If not, is this something I could help with?

**Comment by emilsjolander** [comment]
@joce Feel free to put up a PR of your own. @roxlu is probably busy with other things and would love someone else to help out 👍

**Comment by joce** [comment]
Will look at this then!

**Comment by roxlu** [comment]
Hey @joce and @emilsjolander I've been ill last week and am catching up on work so I won't have any spare time for this until the end of February. @joce my branch with the hide/show feature is here: https://github.com/roxlu/css-layout/tree/feature-hidden-nodes if you want to have a look.

**Comment by joce** [comment]
A major issue I have however is that I'm on Windows, compiling with VisualStudio, and therefore I do not have a C99 compiler. I would need to have this feature based on a branch that compiles in C++98. Is this workable for you?

**Comment by woehrl01** [comment]
@joce I had the same problem. compiling on windows works with vs15 community edition.

**Comment by joce** [comment]
@woehrl01 Excellent! I'll give that a try tonight, then.

**Comment by emilsjolander** [comment]
@joce any update?

**Comment by joce** [comment]
Taken with other fires at work atm.

**Comment by woehrl01** [comment]
@joce @emilsjolander I help out with a new PR #369 with the suggested changes. So you can focus on the fires @joce

**Comment by emilsjolander** [comment]
closing this as @woehrl01 has opened up #369

**Pull request closed without merging**
