### PR TITLE
Create Xcode project so it's much easier to run tests.

### PR DESCRIPTION
**Pull request by dshahidehpour**
I don't even know how people have been running tests (unless they install BUCK). This creates a workspace to make it much easier to run tests.

### CODE REVIEW

**Comment by dshahidehpour** [comment]
@hartbit and @guidomb, if one you could try patching this onto your machine and making sure it works the way you expect, that would be great! :)

**Comment by hartbit** [comment]
@dshahidehpour Yeah, I've been using BUCK up to now, to get as close as possible to the environment travis will run the tests on. But the project is going to help for general development! It's working fine on  my machine.

**Comment by guidomb** [comment]
I was about to test the xcode project but realized that it was removed from master. Why?

**Comment by dshahidehpour** [comment]
We were running into a strange issue with the xcodeproj, and an internal BUCK builds. I'm going to take a look at this during the week and try to resolve it.

**Pull request closed without merging**
