### PR TITLE
[C#][iOS] Fix callbacks on AOT

### PR DESCRIPTION
**Pull request by splhack**
Based on the idea of #386 by @rmarinho

### CODE REVIEW

**Comment by rmarinho** [comment]
Don't we need to free the handle? i think we might need IDisposable ,  free the handle on Dispose, and call Dispose(false) on the Destructor , we can clear parent weak reference too. i think it will help fix the test failing on iOS for parent destructor.

**Comment by splhack** [comment]
In my understanding GCHandle.Alloc with GCHandleType.Weak means we don't need to free the handle, right?

> iOS for parent destructor

maybe iOS mono implementation has different GC timing for that certain situation?

**Comment by rmarinho** [comment]
@splhack i m not a expert but from internal feedback i got that _"Yea, you still need to dispose of the GCHandle manually. "_

**Comment by rmarinho** [comment]
About the test , maybe something around this :

https://github.com/rmarinho/yoga/commit/9a68a14699a038043d4176e5d5ce8b7c965e2b3a

**Comment by splhack** [comment]
Or just skip GC test on iOS?

**Comment by rmarinho** [comment]
sure that's an option ..

**Comment by splhack** [comment]
How about this attempt to call GCHandle.Free?

**Comment by rmarinho** [comment]
👍

**Comment by rmarinho** [comment]
Can we merge this? why is the build failing ?

**Comment by splhack** [comment]
Yeah, we're trying to do that with #386.

**Pull request closed without merging**
