### PR TITLE
Fix: Correct Layout Behavior for Combined align-content and align-items

### PR DESCRIPTION
**Pull request by phuccvx12**
This pull request addresses the issue where combining align-content and align-items properties resulted in incorrect layout behavior in Yoga version 3.1.0, as reported in [Issue #1739](https://github.com/facebook/yoga/issues/1739).

# Changes Made:

Alignment Logic Update: Modified the alignment calculations to ensure that the combination of align-content and align-items properties produces the expected layout, consistent with CSS Flexbox standards and previous Yoga versions.

Test Cases Added: Introduced new test cases to cover scenarios involving various combinations of align-content and align-items properties to prevent future regressions.

# Testing:

All existing tests pass successfully.

New test cases confirm that the layout behaves as expected when align-content and align-items are used together.

# Impact:

This fix ensures that layouts using both align-content and align-items properties render correctly, aligning with the behavior observed in Yoga version 1.19.0 and standard web browsers.

### CODE REVIEW

**Comment by NickGerleman** [comment]
Thank you for the PR! I’m away until next week, where I could look closer, but @joevilches or @rozele may be able to look in the meantime. We have some existing coverage around here, and this adds more tests, which is great!

**Comment by NickGerleman** [comment]
Triggering the CI, it looks like the generated tests might be out of date with the fixture. That usually means it was run on an earlier revision, or more rarely, that the used version of Chrome in CI comes up with different results (Chrome does sometimes change behavior in edge cases to align closer to the spec).

**Comment by joevilches** [comment]
@phuccvx12 I ran `yarn gentest` locally around 7 hours ago and did not see any tests need to change. I also recently added a change that is also failing. Likely an issue with the CI I can take a look

**Comment by joevilches** [comment]
@phuccvx12  I tried again today and was able to repro the Chrome changes. #1746 should fix this action

**Pull request closed without merging**
