### PR TITLE
Improve JS Travis testing

### PR DESCRIPTION
**Pull request by arcanis**
Not ready for merge just yet, just trying some things :)

### CODE REVIEW

**Comment by emilsjolander** [comment]
Thanks! Really appreciate you working on this.

**Comment by arcanis** [comment]
Hm, it seems I can only run a single Travis build or two per day, so it might take some time to find the right settings :/

**Comment by emilsjolander** [comment]
Yup. travis is super slow :/

**Comment by arcanis** [comment]
@emilsjolander

**Pull request closed without merging**
