### PR TITLE
fix wraping calculation if min-size constraint exists

### LINKED ISSUE #261: Combination of flex-shrink, flex-grow, flex-basis and min-width with wrap is not working as expected
To following is not rendered as expected:

```
<div id="wrap_flex_grow_shrink_and_basis" style="width: 80px; flex-wrap: wrap; flex-direction:row;">
 <div style="flex-shrink: 0; flex-grow: 1; flex-basis: 40px; height: 20px; min-width: 50px;"></div>
 <div style="flex-shrink: 0; flex-grow: 1; flex-basis: 40px; height: 20px; min-width: 50px;"></div>
 <div style="flex-shrink: 0; flex-grow: 1; flex-basis: 40px; height: 20px; min-width: 50px;"></div>
 <div style="flex-shrink: 0; flex-grow: 1; flex-basis: 40px; height: 20px; min-width: 50px;"></div>
 <div style="flex-shrink: 0; flex-grow: 1; flex-basis: 40px; height: 20px; min-width: 50px;"></div>
</div>
```

failing test output:
```
[ RUN      ] CSSLayoutTest.wrap_flex_grow_shrink_and_basis
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(389): error: Value of: CSSNodeLayoutGetHeight(root)
  Actual: 60
Expected: 100
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(393): error: Value of: CSSNodeLayoutGetWidth(root_child0)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(396): error: Value of: CSSNodeLayoutGetLeft(root_child1)
  Actual: 50
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(397): error: Value of: CSSNodeLayoutGetTop(root_child1)
  Actual: 0
Expected: 20
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(398): error: Value of: CSSNodeLayoutGetWidth(root_child1)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(402): error: Value of: CSSNodeLayoutGetTop(root_child2)
  Actual: 20
Expected: 40
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(403): error: Value of: CSSNodeLayoutGetWidth(root_child2)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(406): error: Value of: CSSNodeLayoutGetLeft(root_child3)
  Actual: 50
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(407): error: Value of: CSSNodeLayoutGetTop(root_child3)
  Actual: 20
Expected: 60
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(408): error: Value of: CSSNodeLayoutGetWidth(root_child3)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(412): error: Value of: CSSNodeLayoutGetTop(root_child4)
  Actual: 40
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(421): error: Value of: CSSNodeLayoutGetHeight(root)
  Actual: 60
Expected: 100
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(423): error: Value of: CSSNodeLayoutGetLeft(root_child0)
  Actual: 30
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(425): error: Value of: CSSNodeLayoutGetWidth(root_child0)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(428): error: Value of: CSSNodeLayoutGetLeft(root_child1)
  Actual: -20
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(429): error: Value of: CSSNodeLayoutGetTop(root_child1)
  Actual: 0
Expected: 20
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(430): error: Value of: CSSNodeLayoutGetWidth(root_child1)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(433): error: Value of: CSSNodeLayoutGetLeft(root_child2)
  Actual: 30
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(434): error: Value of: CSSNodeLayoutGetTop(root_child2)
  Actual: 20
Expected: 40
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(435): error: Value of: CSSNodeLayoutGetWidth(root_child2)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(438): error: Value of: CSSNodeLayoutGetLeft(root_child3)
  Actual: -20
Expected: 0
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(439): error: Value of: CSSNodeLayoutGetTop(root_child3)
  Actual: 20
Expected: 60
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(440): error: Value of: CSSNodeLayoutGetWidth(root_child3)
  Actual: 50
Expected: 80
c:\users\lukas\dev\css-layout\tests\csslayoutflexwraptest.cpp(444): error: Value of: CSSNodeLayoutGetTop(root_child4)
  Actual: 40
Expected: 80
[  FAILED  ] CSSLayoutTest.wrap_flex_grow_shrink_and_basis (19 ms)
```

### PR DESCRIPTION
**Pull request by woehrl01**
Fixes #261

### CODE REVIEW

**Comment by woehrl01** [comment]
this also fixes, that you have to take padding and border into account on space distribution.

**Comment by emilsjolander** [comment]
Looks good. I'll merge it this week. Thanks!

**Comment by emilsjolander** [comment]
When importing this I noticed it broke some internal product tests. So I investigated and boiled it down to the following tests which breaks when applying this diff.

```html
<div style="width: 200px; height: 200px; justify-content: flex-end;">
  <div style="width: 100px; height: 100px; padding: 20px;"></div>
</div>
```

I'll add this test to the test suite

**Comment by woehrl01** [comment]
Thanks! I will have a look!

**Comment by woehrl01** [comment]
puh 😄 finally got the logic right. 
It seams there is a difference if the container is ```flex-wrap: wrap``` or not. So I added a bunch of test cases. But all in all they are running fine now.

Do you have additional test cases in your internel test suite which are failing with these changes?

**Comment by emilsjolander** [comment]
I've re-imported and rebased this pull request. All looks good as far as tests go. I'm not quite understanding the change though so I would love it if you could explain what is going on here. Why are we only including the padding of a child in its size calculation if flex is set to wrap?

**Comment by woehrl01** [comment]
@emilsjolander I'm not sure why this is. I couldn't find something like this in the spec. My theorie is, that under chrome ```box-sizing: border-box``` is not correctly applied if flex wrapping is enabled. I changed ```test-template.html``` to use ```box-sizing: content-box``` and the same expected values got generated, which should not, shouldn't it? I'm torn back and forth with this change, it is required to make the tests pass against the chrome implementation, but I don't fully understand the switch on flex-wrap either. I think it is required to be confident about the output (if you use chrome as reference) and to make some gentests pass, which wouldn't otherwise. I haven't checked the output with other browsers yet. Should we hide this behind a feature flag, how about tests then?

**Comment by emilsjolander** [comment]
@woehrl01 lol css has a bunch of unexplainable things, just wondering your thoughts behind this. Thanks! It would be awesome if you could check the output in other browsers. I've previously had issues with `flex-wrap` being implemented slightly differently in different browsers causing different behavior in all major browsers (yuck). Regarding feature flag and tests I recently added support for feature flags in generated tests 👍 Not saying we should do this but in case we do there is support for it (pixel rounding uses this).

**Comment by emilsjolander** [comment]
@woehrl01 did you get a chance to check out other browsers?

**Comment by woehrl01** [comment]
@emilsjolander I looked at the output on Edge 38, Firefox 50 and Chrome 54. They are all producing the same output. So I think that my theory is wrong. But I have another theory, based on a deeper look on the generated values without this fix. I think that my changes are a workaround for a bug inside the library, where under the condition of no wrap the values are added a second time later in the algorithm. I think the current "fix" is enough at the current time. When I have a little more time, I'll take the spec and will have a drill down on where the possible bug is hiding. What do you think?

**Comment by emilsjolander** [comment]
@woehrl01 sounds good. I might take a look at it as well. Thanks!

**Comment by woehrl01** [comment]
@emilsjolander what's the/your current state of this PR?

**Pull request closed without merging**
