### PR TITLE
Fixes compilation for react-native-windows.

### PR DESCRIPTION
**Pull request by rozele**
Updates the following for compatibility with the latest react-native-windows:
- NuGet dependencies
- *.vcxproj and *.csproj files
- Removes designated initializer syntax

### CODE REVIEW

**Comment by rozele** [comment]
Similar to #700, except comments out designated initializers instead of removing them. cc @matthargett @priteshrnandgaonkar @woehrl01.

**Comment by priteshrnandgaonkar** [comment]
@rozele We can have a macro which handles this case. Follow #700 PR thread.

**Comment by rozele** [comment]
Closing in favor of #716

**Comment by rozele** [comment]
Re-opening - I don't think the macro is the way to go here. Can we please merge this and deal with the macro in a follow up PR? I'd like to start using C++ code that ships in the react-native NPM package in react-native-windows ASAP.

**Comment by rozele** [comment]
Ultimately, it all comes down to readability. Computers don't care about macros. IMO the following:
```
/* .position = */ {},
```
Is much more readable than:
```
DESIGNATED_INITIALIZER(position, {})
```
I understand that using the macro might make it clear that we're removing the designated initializer specifically for Windows, but I don't think it's worth the tradeoff in readability.

**Comment by priteshrnandgaonkar** [comment]
I think we can use contructors. Whats your take @rozele

**Comment by priteshrnandgaonkar** [comment]
Its an easy fix to have a constructor, it shouldn't take time. Let's not land the hacky solution, even if I import it, it would be rejected in an internal review.

**Comment by rozele** [comment]
@priteshrnandgaonkar - if it's easy, do you mind taking the first crack at it? Since you're connected internally, you'll know better what's not going to be rejected on review. I'll happily test on windows once you have a branch.

**Comment by matthargett** [comment]
“hacky” doesn’t seem like an appropriate characterization, in my opinion, for what it’s worth. Please just let the community know the non-C++20 syntax most likely to be accepted. Thanks! :)

**Comment by priteshrnandgaonkar** [comment]
I am on it. Will add a change related to constructors which I am talking about. Then you can rebase your changes on it.

**Comment by priteshrnandgaonkar** [comment]
My changes are merged, you can rebase it.

**Comment by rozele** [comment]
Thanks @priteshrnandgaonkar. We're now building from Yoga source in react-native-windows, similar to how it works for iOS and Android. I'll likely copy the .vcxproj files into the react-native-windows repo so we can manage them more easily there. I plan to continue using the Facebook.Yoga.Shared C# project as a submodule in react-native-windows. I'm closing this PR.

**Comment by rozele** [comment]
Re-opening, there were also some changes in this PR related to DLL exports that should be merged.

**Comment by rozele** [comment]
@priteshrnandgaonkar - it looks like we're still missing constructors for YGValue and YGConfig.

**Pull request closed without merging**
