### PR TITLE
fix print edge value.

### PR DESCRIPTION
**Pull request by yihuang**

### CODE REVIEW

**Comment by woehrl01** [comment]
@yihuang I saw your new commits unrelated to the edge fix, which changes the values which are passed to the margin calculations. Some of them aren't correct anymore, percentage margins are always calculated based on the width of the parent.

**Comment by yihuang** [comment]
@woehrl01 Yes, I'm wrong about percentage margins, but percentage bottom should based on the height of parent, right?

**Comment by yihuang** [comment]
@woehrl01 I've edited the problematic commits about margin values, and the title of PR to include the fix for right/bottom value.

**Comment by emilsjolander** [comment]
@yihuang Could you please separate this into two PRs ? One for the print change and another for the absolute layout fix.

**Comment by yihuang** [comment]
@emilsjolander Done.

**Pull request closed without merging**
